"""empty message

Revision ID: 9fed0545f849
Revises: c030e9eee127
Create Date: 2017-11-14 19:23:38.331382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fed0545f849'
down_revision = 'c030e9eee127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_fcm_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_fcm_token')
    # ### end Alembic commands ###
